# Cloud Build configuration for automatic deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flashcard-mcp-server:$COMMIT_SHA', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flashcard-mcp-server:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flashcard-mcp-server'
      - '--image=gcr.io/$PROJECT_ID/flashcard-mcp-server:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60'
      - '--concurrency=1000'
      - '--min-instances=0'
      - '--max-instances=100'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest'

# Store image in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/flashcard-mcp-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'